import AboutContainer from "@/Components/container/AboutContainer";
import styles from "./page.module.css";
import dummyImage from "../../../public/lading-container.jpg";
import ParagraphContainer from "@/Components/container/ParagraphContainer";

export default function Page() {
    return (
        <div className={styles.projects_page}>
            <div className={styles.projects_title}>
                <span>Conheça Meus Projetos</span>
            </div>
            <ParagraphContainer
                image={dummyImage}
                paragraph="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit. Non odio euismod lacinia at quis risus sed vulputate. Pharetra vel turpis nunc eget lorem dolor sed. Sed adipiscing diam donec adipiscing tristique. Elementum sagittis vitae et leo duis ut. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Varius duis at consectetur lorem donec massa sapien. Neque laoreet suspendisse interdum consectetur libero id. Orci sagittis eu volutpat odio facilisis. Mauris a diam maecenas sed enim. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Laoreet suspendisse interdum consectetur libero id. Velit egestas dui id ornare arcu odio ut sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit."
            />
            <div className={styles.projects_page_label}>
                <span>Projeto 1 &bull; Projeto 2</span>
            </div>
            <AboutContainer
                imageOne={dummyImage}
                imageTwo={dummyImage}
                paragraphOne="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit. Non odio euismod lacinia at quis risus sed vulputate. Pharetra vel turpis nunc eget lorem dolor sed. Sed adipiscing diam donec adipiscing tristique. Elementum sagittis vitae et leo duis ut. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Varius duis at consectetur lorem donec massa sapien. Neque laoreet suspendisse interdum consectetur libero id. Orci sagittis eu volutpat odio facilisis. Mauris a diam maecenas sed enim. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Laoreet suspendisse interdum consectetur libero id. Velit egestas dui id ornare arcu odio ut sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit."
                paragraphTwo="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit. Non odio euismod lacinia at quis risus sed vulputate. Pharetra vel turpis nunc eget lorem dolor sed. Sed adipiscing diam donec adipiscing tristique. Elementum sagittis vitae et leo duis ut. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Varius duis at consectetur lorem donec massa sapien. Neque laoreet suspendisse interdum consectetur libero id. Orci sagittis eu volutpat odio facilisis. Mauris a diam maecenas sed enim. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Laoreet suspendisse interdum consectetur libero id. Velit egestas dui id ornare arcu odio ut sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit."
            />
            <div className={styles.projects_page_label}>
                <span>Projeto 3</span>
            </div>
            <ParagraphContainer
                image={dummyImage}
                paragraph="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit. Non odio euismod lacinia at quis risus sed vulputate. Pharetra vel turpis nunc eget lorem dolor sed. Sed adipiscing diam donec adipiscing tristique. Elementum sagittis vitae et leo duis ut. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Varius duis at consectetur lorem donec massa sapien. Neque laoreet suspendisse interdum consectetur libero id. Orci sagittis eu volutpat odio facilisis. Mauris a diam maecenas sed enim. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Laoreet suspendisse interdum consectetur libero id. Velit egestas dui id ornare arcu odio ut sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elementum eu facilisis sed odio morbi quis commodo odio. Vitae proin sagittis nisl rhoncus mattis rhoncus. Lacinia quis vel eros donec ac odio tempor orci. Arcu odio ut sem nulla pharetra diam sit."
            />
        </div>
    );
}
